### ISSUE TITLE
Shelf 1.1.1 breaking change: request body runtime type changed from Stream<List<int>> to Stream<Uint8List>

### ISSUE THREAD

**Issue by nex3** [dart-lang/shelf#189] opened 2021-05-18 22:04 UTC
Shelf 1.1.1 introduced a breaking change. By changing the runtime type of request bodies from `Stream<List<int>>` to `Stream<Uint8List>`, it caused it to no longer work with instances of `StreamTransformer<List<int>, List<int>>` such as `dart:io`'s `gzip.encoder` and `gzip.decoder`. This is a breaking change and, if it was necessary, should have been released with a major version bump.

The following code works with shelf 1.1.0 and not with 1.1.1:

```dart
import 'dart:io';

import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf/shelf_io.dart' as shelf_io;

Future<void> main() async {
  var server = await shelf_io.serve((request) async {
      await request.read().transform(gzip.decoder).drain();
      return shelf.Response.ok("");
    }, "localhost", 0);

  var client = HttpClient();
  var request = await client.post("localhost", server.port, "/");
  await request.close();
  client.close(force: true);
  server.close();
}
```

**Comment by kevmoo** [comment] 2021-05-18 22:35
CC @natebosch @jonahwilliams

**Comment by kevmoo** [comment] 2021-05-18 22:41
Yeah, very unintentional.

Before we were ALWAYS wrapping the input in `List<int>` which turned out to be very expensive. Now we just flow through the input bits.

The question now: do we revert and give up the perf win?

This is a ~duplicate of https://github.com/dart-lang/shelf/issues/188 – leaving open to discuss

**Comment by nex3** [comment] 2021-05-18 23:01
Whether or not you choose to release the `cast`-free implementation, the 1.x branch should continue to `cast()` because doing otherwise is a breaking change.

**Comment by zambetpentru** [comment] 2021-07-20 21:18
Hi, as raised in https://github.com/dart-lang/shelf/issues/193 I am trying to find the best way now to receive a large file upload. Is there a recommended example?

**Comment by kevmoo** [comment] 2021-07-21 03:00
Just got to put the converter first:

```diff
diff --git a/example/mime.dart b/example/mime.dart
index 1975ead..a5735a9 100644
--- a/example/mime.dart
+++ b/example/mime.dart
@@ -6,7 +6,7 @@ import 'package:shelf/shelf_io.dart' as shelf_io;
 Future<void> main() async {
   var server = await shelf_io.serve(
     (request) async {
-      await request.read().transform(gzip.decoder).drain();
+      await gzip.decoder.bind(request.read()).drain();
       return shelf.Response.ok('');
     },
     'localhost',
```

**Comment by Silentdoer** [comment] 2021-12-13 23:41
this bug has been fixed?

**Closed** 2022-03-22 21:47 UTC
Labels: bug

**Comment by Silentdoer** [comment] 2022-10-11 07:02
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
