### ISSUE TITLE
Help Wanted: Streaming Data chunks from a Shelf Server

### ISSUE THREAD

**Issue by mark-at-pieces** [dart-lang/shelf#375] opened 2023-08-23 21:55 UTC
Hey all,

First, thank you for the wonderful Dart package! 

My goal is to have an endpoint that will accept a post body and then basically send incremental chunks of data as we complete the processing.

I found a couple ways to do, here is a mock'd example where I would return the controller.stream immediately and then process the chunks in the background incrementally send then as they finish.

```dart
Future<Response> _echoRequest(Request request) async {
    var controller = StreamController<List<int>>();

    // Start an async task to send chunks
    Future(() async {
      for (int i = 0; i < 10; i++) {
        // Send size of the chunk in hexadecimal followed by CRLF
        controller.add('${'Chunk $i'.length.toRadixString(16)}\r\n'.codeUnits);
        // Send the chunk followed by CRLF
        controller.add('Chunk $i\r\n'.codeUnits);
        // Delay to simulate processing
        await Future.delayed(Duration(seconds: 1));
      }

      // Final chunk (size 0) followed by CRLF, and then end with another CRLF
      controller.add('0\r\n\r\n'.codeUnits);
      controller.close();
    });

    return Response(200, body: controller.stream, headers: {
      'Transfer-Encoding': 'chunked',
      'Content-Type': 'text/plain',
    });
  }
  ```
  
  I found, however that the chunks don't send over to the client untill the controller has been fully closed.
  
  I'm wondering if I'm doing something wrong here and was wondering if you all could help me out.
  
 Another solution that I know will work is just default to websockets, but figured I would ask anyways.
 
 Thanks,
 Mark

**Comment by kevmoo** [comment] 2023-08-24 19:46
See the docs here: https://pub.dev/documentation/shelf/latest/shelf_io/shelf_io-library.html

WRT to `shelf.io.buffer_output` – closing as not a bug, but happy to offer guidance if you repyl.

**Closed by kevmoo** 2023-08-24 19:46 UTC
Labels: package:shelf

**Comment by mark-at-pieces** [comment] 2023-08-24 21:13
@kevmoo this worked great thank you!
