### ISSUE TITLE
Streaming files from Multipart Request - Error:type 'MimeMultipartTransformer' is not a subtype of type 'StreamTransformer<Uint8List, MimeMultipart>' of 'streamTransformer'

### ISSUE THREAD

**Issue by zambetpentru** [dart-lang/shelf#193] opened 2021-06-18 19:36 UTC
Hi,

I am trying to figure out the best way to receive a Multipart video file from a HTTP Post in shelf without loading the whole file into memory.

I tried to follow the example here from a year ago: https://gist.github.com/alexd1971/67f4502c5e0d594d30f901fb0559fd7e
but it doesn't work (any more?) and I get the error:

**Error:type 'MimeMultipartTransformer' is not a subtype of type 'StreamTransformer<Uint8List, MimeMultipart>' of 'streamTransformer'**

        **await for (MimeMultipart part in request.read().transform(new MimeMultipartTransformer(header.parameters['boundary']!))) {**
          if (part.headers.containsKey('content-disposition')) {
            header = HeaderValue.parse(part.headers['content-disposition']!);
            // String filename = header.parameters['filename'];
            final file = await File('/destination/filename.mp4')
                .create(recursive: true); //Up two levels and then down into ServerFiles directory
            IOSink fileSink = file.openWrite();
            await part.pipe(fileSink);
            fileSink.close();

After many different iterations the following does work but it very memory intensive with the Int arrays:

     List<int> dataBytes = [];
        await for (var data in request.read()) {
          dataBytes.addAll(data);
        }

        String fileExtension = '';
        late File file;
        final transformer = MimeMultipartTransformer(header.parameters['boundary']!);
        final bodyStream = Stream.fromIterable([dataBytes]);
        final parts = await transformer.bind(bodyStream).toList();
        final part = parts[0];
        if (part.headers.containsKey('content-disposition')) {
          header = HeaderValue.parse(part.headers['content-disposition']!);
          originalfilename = header.parameters['filename'];
          print('originalfilename:' + originalfilename!);
          fileExtension = p.extension(originalfilename);
          file = await File('/destination/filename.mp4')
              .create(recursive: true); //Up two levels and then down into ServerFiles directory
          final content = await part.toList();
          await file.writeAsBytes(content[0]);
         }

**Comment by kevmoo** [comment] 2021-06-18 23:50
Duplicate of https://github.com/dart-lang/shelf/issues/189 – FYI @natebosch

**Closed by kevmoo** 2021-06-18 23:50 UTC

**Comment by zambetpentru** [comment] 2021-07-20 21:19
Hi @kevmoo, is there a better way to do the above that doesn't take multiples the amount of RAM as the uploaded file size?

**Comment by kevmoo** [comment] 2021-07-21 03:04
Use `transformer.bind(request.read())` – that'll work!
